FROM envoyproxy/envoy-dev:27084341f110132fbb13792c81e97aeebf682436
ENV PATH=${PATH}:/usr/local/go/bin:/opt/workdir/.go/bin
ENV GOPATH=/opt/workdir/.go
ENV GOCACHE=/opt/workdir/.go/.cache

WORKDIR /opt/workdir
RUN apt update -y \
    && apt install curl wget vim git gcc make apt-transport-https gnupg2 lsb-release -y \
    && curl -sL 'https://deb.dl.getenvoy.io/public/gpg.8115BA8E629CC074.key' | gpg --dearmor -o /usr/share/keyrings/getenvoy-keyring.gpg \
    && echo a077cb587a1b622e03aa4bf2f3689de14658a9497a9af2c427bba5f4cc3c4723 /usr/share/keyrings/getenvoy-keyring.gpg | sha256sum --check \
    && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/getenvoy-keyring.gpg] https://deb.dl.getenvoy.io/public/deb/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/getenvoy.list \
    && apt update -y && apt install -y getenvoy-envoy
ADD manifests/envoy.yaml envoy.yaml
RUN wget https://go.dev/dl/go1.19.1.linux-amd64.tar.gz
RUN rm -rf /usr/local/go \
    && tar -C /usr/local -xzf go1.19.1.linux-amd64.tar.gz \
    && mkdir -p /opt/workdir/.go/github.com \
    && rm -fr go1.19.1.linux-amd64.tar.gz
RUN go install github.com/go-delve/delve/cmd/dlv@latest

CMD ["/bin/bash", "-c", "sleep inf"]